# Etcd cluster in Docker
# https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/container.md#docker
#
version: '3.1'
services:
  etcd-node:
    image: etcd:3.3.12-alpine
    build:
      context: ./etcd
    environment:
    - ETCD_RUNNING_MODE=node
    - ETCD_WAIT_FOR_START=2
    networks:
    - net_etcd
    volumes:
    - vol_etcd:/etcd-data

  etcd-proxy:
    image: etcd:3.3.12-alpine
    build:
      context: ./etcd
    environment:
    - ETCD_RUNNING_MODE=proxy
    - ETCD_NODE_SERVICE=etcd-node
    networks:
    - net_etcd
    depends_on:
    - etcd-node

networks:
  net_etcd:

volumes:
  vol_etcd:
