# Etcd cluster in Docker
# https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/container.md#docker
#
version: '3.1'
services:
  etcd-node:
    image: etcd-node:3.3.12-alpine
    build:
      context: .
      args:
      - mode=node
    networks:
    - net_etcd
    volumes:
    - vol_etcd:/etcd-data

  etcd-proxy:
    image: etcd-proxy:3.3.12-alpine
    build:
      context: .
      args:
      - mode=proxy
    environment:
    - ETCD_SERVICE_NAME=etcd-node
    networks:
    - net_etcd
    depends_on:
    - etcd-node

networks:
  net_etcd:

volumes:
  vol_etcd:
